### ISSUE TITLE
ShadowRun.exe: Add option for quiet mode

### ISSUE THREAD

**Issue by hhonisch** [albertony/vss#2]
Could you add a command line option for a "quiet mode" where ShadowRun outputs fewer messages? 
I have a use case where ShadowRun passes some "secret" command line argument to the command that it executes, but unfortunately ShadowRun's output "Executing command:..." makes that secret visible. by echoing all command line arguments to the console.

**Comment by albertony** [comment]
That is a good idea, thank you for suggesting it. Perhaps it could be opposite: Default quiet, with option for "verbose mode". Will look into it.

**Comment by albertony** [comment]
Sorry for the long wait, but I finally had some time to look into this. Actually did look into it a while ago as well, but then tried to make it configurable whether to route ShadowRun output to console or file, stdout or stderr, etc, which turned out to be more time consuming than what I had available.. I have now pushed a simpler update which reduces the default amount of output (e.g. not showing command-line arguments as was your concern), and also making it configurable with a new option `--log-level`. Please check out release 0.5.2 or newer.
